### PR TITLE
Add layer tint color; Fix `Color` parsing issues

### LINKED ISSUE #85: Parse layers' tint color
It would be great if we could get [the tint color of layer](https://thorbjorn.itch.io/tiled/devlog/120663/tinting-alignment-and-object-references). This would avoid duplicating it in properties (which can cause a bugs). I can try to implement this.

### LINKED ISSUE #148: Color parsing does not take `alpha` into account
The `Color` structure does not keep track of the alpha value of the color, and the `FromStr` implementation of `Color` is wrong since it assumes that colors are in the `#RRGGBB` format (as opposed to `#AARRGGBB`)

### LINKED ISSUE #149: Add `Color` tests
Add tests for parsing colors.

### PR DESCRIPTION
**Pull request by alexdevteam**
Closes #149, closes #85, fixes #148.

### CODE REVIEW

**Comment by alexdevteam** [comment]
I thought this would be my first nonbreaking PR, but sadly the addition of the `alpha` member in `Color` makes it breaking. Sad

File: src/properties.rs [hunk 1]
```diff
@@ -1,38 +1,61 @@
...
-            return Ok(Color {
-                red: r.unwrap(),
-                green: g.unwrap(),
-                blue: b.unwrap(),
-            });
+    fn from_str(s: &str) -> Result<Color, Self::Err> {
+        let s = if s.starts_with("#") {
+            &s[1..]
+        } else {
+            return Err(());
```
Comment (bjorn) [inline src/properties.rs:25]: Actually, taking `s` as a fallback is what we need to do, because for backwards compatibility reasons, the `trans` attribute on the `image` element leaves out the `#` but is otherwise a valid color value.

(and this is actually documented for once ;-))

**Review by bjorn — CHANGES_REQUESTED** [review]
Looking good, just one small issue.

**Review by bjorn — DISMISSED** [review]

**Comment by bjorn** [comment]
Wait a sec, you're still missing the changelog entry!

**Review by bjorn — APPROVED** [review]
